name: GitHub Actions Demo
run-name: Running PHPUnit
on: [ push ]
jobs:
  PHPUnit:
    strategy:
      matrix:
        php: [ '8.1', '8.2' ]
        lowest: [ '0','1' ]

    runs-on: ubuntu-latest
    steps:

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, intl
          coverage: xdebug
          tools: composer:v2

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Download phing
        run: mkdir bin && curl -L -C - -s -S -o bin/phing https://github.com/phingofficial/phing/releases/download/3.0.0-rc6/phing-3.0.0-RC6.phar && chmod +x bin/phing

      - name: Composer update
        run: composer update
        env:
          COMPOSER_PREFER_LOWEST: ${{ matrix.lowest }}

      - name: Composer install
        run: bin/phing composer:install

      - name: PHPUnit
        run: bin/phing phpunit:check


