name: Quality Assurance
on: [ pull_request ]
jobs:
  QA:
    strategy:
      matrix:
        php: [ '8.1', '8.2', '8.3' ]
        dependencies: [ highest, lowest ]

    runs-on: ubuntu-latest
    steps:

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, intl
          coverage: xdebug

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install phing
        env:
          PHING_VERSION: '3.0.0'
        run: |
          mkdir -p ~/.local/bin
          curl -L -C - -s -S -o ~/.local/bin/phing https://github.com/phingofficial/phing/releases/download/${PHING_VERSION}/phing-${PHING_VERSION}.phar
          chmod +x ~/.local/bin/phing

      - name: Install dependencies
        run: composer update --no-interaction ${{ matrix.dependencies && '' || '--prefer-lowest' }}

      - name: Quality assurance
        run: phing qa
