name: Quality Assurance
on: [ pull_request ]
jobs:
  QA:
    strategy:
      matrix:
        php: [ '8.1', '8.2', '8.3' ]
        dependencies: [ highest, lowest ]

    runs-on: ubuntu-latest
    steps:

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, intl
          coverage: xdebug
          tools: phing:v3.0.0

      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: "ramsey/composer-install@v3"
        with:
          dependency-versions: "${{ matrix.dependencies }}"

      - name: Quality assurance
        run: phing qa
